#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{myresume}
#+LaTeX_HEADER: \hypersetup{hidelinks}
#+LaTeX_CLASS_OPTIONS: [letterpaper]
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#+LaTeX_HEADER: \usepackage{paralist}
#+LaTeX_HEADER: \let\itemize\compactitem

# Palatino
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{mathpazo}
#+LaTeX_HEADER: \linespread{1.05}
#+LaTeX_HEADER: \usepackage[scaled]{helvet}
#+LaTeX_HEADER: \usepackage{courier}

{{{HEADER}}}

* Education
** *Victoria University of Wellington* (Wellington, NZ)
*** 2019-June 2020
Master of Arts, Linguistics
** *Victoria University of Wellington* 
*** 2016-2018
Bachelor of Arts, Linguistics

* Research Experience
** *MA programme, Victoria University of Wellington*
*** 2020-present
- Building on summer research internship, conducted independent research on comparative syntactic typology of Austronesian languages and its relation to new findings in Austronesian/Malayo-Polynesian subgrouping models, archaeology, and genetics.
- Presented my findings as part of the 2020 LALS seminar series.
** *Summer research internship, Victoria University of Wellington*
*** 2019-2020
- Working closely with Dr. Victoria Chen, conducted a detailed survey of the syntactic typology of 43 Austronesian languages sampled from all primary branches of Austronesian, and all primary branches of Malayo-Polynesian as identified in the most recent subgrouping model proposed by Alexander Smith (2017).
- Created typological maps of this data using QGIS and Python.
** *Honours Phonology research project*
*** 2019
- Conducted an original research project on Solomon Islands Pijin an English/Oceanic creole language.
- Recorded utterance data from native speakers of Solomon Islands Pijin I recruited from the community.
- Conducted phonological analysis on this data using PRAAT, verifying the assertion made in the literature for this language that the metrical structure of Pijin words reflects their lexical origin in English or Oceanic languages.

* Relevant Work Experience
** *Operations analyst - TranscribeMe, Inc.*
*** 2012-2015
- Recruited for, built and coordinated a processing pipeline for crowdsourced transcription for x hours per day of call centre audio from a major New Zealand agricultural company.
- Developed custom reporting, management and training software for the operations team using Python and MS SQL Server.

* Honors
- Master of Arts degree awarded with Distinction
- Included on Dean's List for academic excellence, 2016.

* Skills
- Computing :: Python, SQL/PostgreSQL, R, Common Lisp, Linux system administration, Git, \LaTeX, QGIS, HTML/CSS/Javascript, functional programming, algorithm design.
- Linguistics :: Data collection and experiment design; Analytical techniques for syntax, historical linguistics, phonetics and phonology

* Research interests

Austronesian languages, historical linguistics, syntax, typology, linguistic anthropology, contact linguistics.

